### ISSUE TITLE
How is this different to or similiar to tidyfast?

### ISSUE THREAD

**Issue by xiaodaigh** [hope-data-science/tidyfst#1]
See https://github.com/TysonStanley/tidyfast

**Comment by hope-data-science** [comment]
*tidyfast* seems to focus on analogous in *tidyr* only, *tidyfst* do not have any boundary. Nevertheless, *tidyfst* is acutually learning from all these packages, and about the nesting part I got many inspirations from *tidyfast*. Nevertheless, *tidyfst* supports *fst*, has super selector with `select_dt`, and many many more features that you might not find equivalent so far. Keep the updates~~

**Comment by xiaodaigh** [comment]
So seems to have some common goals as https://github.com/fstpackage/fsttable

**Comment by hope-data-science** [comment]
I did not know about this work before, and I think the syntax is quite different.
