### ISSUE TITLE
select_dt seems couldn't select more than 7 columns

### ISSUE THREAD

**Issue by fc-ibb105** [hope-data-science/tidyfst#12]
select_dt seems couldn't select more than 7 columns

`Warning message:
In if (is.na(dot_string)) dt else if (str_detect(dot_string, "^[-,0-9 ]+$")) eval(parse(text = str_glue("dt[,c({dot_string})]"))) else if (str_detect(dot_string,  :
  条件的长度大于一，因此只能用其第一元素`

**Comment by hope-data-science** [comment]
Hello, would you please give me some codes so I can replicate your situation? Thanks.

**Comment by fc-ibb105** [comment]
library(tidyfst)
load(“d.rData”)
d %>% select_dt(seqnames,
            TSS_start,
            TSS_end,
            gene_id,
            gene_name,
            Group,
            log2FC)


Warning message:
In if (is.na(dot_string)) dt else if (str_detect(dot_string, "^[-,0-9 ]+$")) eval(parse(text = str_glue("dt[,c({dot_string})]"))) else if (str_detect(dot_string,  :
  条件的长度大于一，因此只能用其第一元素


When I delete any one from  the 7 columns, it works.
When I using dplyr::select(), it works.
And it’s actually not the first time not working.
That’s why I assume it may not working over 7 columns.

Howerver, when I tried the following codes, it works, I’m now confused, may it suitable for my data.

data.table(matrix(1:100,c(10,10)) %>% select_dt(V1,V3,V2,V4,V5,V6,V8,V10,V9)
       V1    V3    V2    V4    V5    V6    V8   V10    V9
    <int> <int> <int> <int> <int> <int> <int> <int> <int>
1:     1    21    11    31    41    51    71    91    81
2:     2    22    12    32    42    52    72    92    82
3:     3    23    13    33    43    53    73    93    83
4:     4    24    14    34    44    54    74    94    84
5:     5    25    15    35    45    55    75    95    85
6:     6    26    16    36    46    56    76    96    86
7:     7    27    17    37    47    57    77    97    87
8:     8    28    18    38    48    58    78    98    88
9:     9    29    19    39    49    59    79    99    89
10:    10    30    20    40    50    60    80   100    90

发件人: ***@***.***>
发送时间: 2021年4月25日 9:10
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [hope-data-science/tidyfst] select_dt seems couldn't select more than 7 columns (#12)


Hello, would you please give me some codes so I can replicate your situation? Thanks.

―

**Comment by hope-data-science** [comment]
I can select more than 7 columns, so I don't understand why you could not. Maybe you could make the data available to me so I can understand why it didn't work.
