### ISSUE TITLE
`dummy_dt()` fails when `NA`s are present

### ISSUE THREAD

**Issue by markfairbanks** [hope-data-science/tidyfst#15]
``` r
library(tidyfst)

df <- data.table(x = c("a", "b", NA))

df %>%
  dummy_dt(x)
#> Error: NA in 'new' at positions [3]
```

**Comment by hope-data-science** [comment]
This is interesting. When we make dummy variables, we suppose these values would finally become (part of the) variable name. A good practice is fill the NA before making dummy variables. No one would like the column name to be "NA", this could be ambiguous.

**Comment by markfairbanks** [comment]
Flagging a variable as NA is useful in modeling, even if filling/imputation is done afterwards.

> No one would like the column name to be "NA", this could be ambiguous.

Then could the auto-generated name be something different? Or the user can just rename afterwards.

**Comment by hope-data-science** [comment]
Flagging a value as NA is useful, but making a dummy variable on such value is not. 

Auto-generating is good, but auto-generate what name? I think giving an error with message to guide users to fill them might be more proper. This could first let them notice there are NAs in their columns (they may not always know), and let them decide what to use as the name for NA (but not give the name all at once).

What do you think?

**Comment by markfairbanks** [comment]
> Flagging a value as NA is useful, but making a dummy variable on such value is not.

This is actually very useful. Sometimes the fact that it is missing is useful in modeling. Even if you impute the value later the fact that it was originally missing can be informative.

> Auto-generating is good, but auto-generate what name?

The name should probably follow the same semantics as the rest of the names. `longnames = TRUE` takes care of any ambiguity. So in this case the name would be `x_NA`, just like the other columns have an `x` prefix.

``` r
library(tidyfst)

df <- data.table(x = c("a", "b", NA))

df %>%
  dummy_dt(x)
#>      x_a   x_b  x_NA
#>    <num> <num> <num>
#> 1:     1     0     0
#> 2:     0     1     0
#> 3:     0     0     1
```

> This could first let them notice there are NAs in their columns (they may not always know)

If they didn't know originally, the presence of a `col_NA` column would alert them. Having a warning would probably be redundant.

**Comment by hope-data-science** [comment]
Then what if the column contains strings of "NA". Any solutions?

**Comment by markfairbanks** [comment]
Looks like this was addressed
