### ISSUE TITLE
dplyr::across

### ISSUE THREAD

**Issue by kongdd** [hope-data-science/tidyfst#16]
Dear @hope-data-science, 

Any idea how to implement `dplyr::across` in `tidyfst`?
https://dplyr.tidyverse.org/reference/across.html

Thank u.

**Comment by hope-data-science** [comment]
Thank you for the comment. Try `mutate_vars` (which should be more simple in syntax), if you have any cases that could not be compelted, let me know.

Thanks.

**Comment by kongdd** [comment]
Thanks for your quick response. I will have a try.

PS: 
Just come across another issue, 
do you know which function should I use to replace `dplyr::n()`? 

Thank u.

**Comment by hope-data-science** [comment]
Use `.N` could replace `dplyr::n()`, this is the syntax in data.table.

**Comment by kongdd** [comment]
Great. Thank u

**Comment by kongdd** [comment]
It seems that tidyfst fail to improve the speed in my case:

```R
library(data.table)
library(tidyfst)

df_path <- fread("data-raw/char_path_Tmax_CN05.1_1961_2021.csv")

cal_path2temporal <- function(df_path) {
  df_path %>% 
  group_exe_dt(
    summarise_dt(
      doy_first = first(doy),
      doy_last = last(doy),
      HWD = .N,
      HWI = mean(anom_mean), # degC
      HWS_mean = sum(anom_mean), # degC d
      HWS_sum = sum(anom_sum), # degC km^2 d
      HWA_avg = mean(area),
      HWA_max = max(area),
      HWA_sum = sum(area)
    )
  ) %>% 
  mutate(across(HWS_sum:HWA_sum, ~ divide_by(.x, 1000))) # convert to 1e6 km^3
}

system.time({
  tmp <- df_path %>%
    group_by_dt(prob, year, id) %>%
    cal_path2temporal()
})
```
```R
user  system elapsed 
  53.89    0.71   56.03
```
In dplyr, it costs about 3s.
Do you have better solution?

The input file: [char_path_Tmax_CN05.1_1961_2021.csv](https://github.com/hope-data-science/tidyfst/files/9166002/char_path_Tmax_CN05.1_1961_2021.csv)

**Comment by hope-data-science** [comment]
Thank you for the comment. Do not use `group_exe_dt`, use the `by` parameter for grouping in `summarize_dt` and try again. 
Thanks.

**Comment by kongdd** [comment]
Indeed, this solution works: `summarize_dt(,..., by)`.
```R
user  system elapsed 
   0.02    0.00    0.01
```
vs.
```R
 user  system elapsed 
   2.72    0.11    2.83
```

But could you tell me why `group_by_dt` and `group_exe_dt` are not suggested?

**Comment by hope-data-science** [comment]
This is a trick in the data.table package. While I favor the syntax `group_by` in dplyr, in data.table the `by` parameter is efficient and faster. These two syntax could hardly be "translated". The best way is to get a `by` parameter for every function that would involve grouping. 

By using `group_by_dt` and `group_exe_dt`, they use `.SD` in data.table, `.SD` is slow in the case of grouping. These functions are intending to let users in dplyr to transit to data.table, consider tidyfst as data.table companion would be best. I would consider how to make them efficient as well if possible. But currently, I don't think there is an easy way to do it.

**Comment by kongdd** [comment]
Got it. You make me realize how slow the `dplyr::group_by` is. I also agree that the syntax of `dplyr` is more elegant than `data.table`.
Thanks for your great work.

**Comment by kongdd** [comment]
Dear @hope-data-science 

Could you give some suggestion how to translate the following script?
```R
library(data.table)
library(dplyr)
df_char = fread("df_char.csv")

vars_mean <- c("u", "v", "speed", "angle")
vars_sum <- c("dist", "angle") # "u", "v"

df_char %>%
  summarise(
    duration = n(),
    across(all_of(vars_mean), mean),
    across(all_of(vars_sum), sum, .names = "{.col}_sum")
  )
```

In my understanding, `tidyfst::summarise_vars` should be called twice, and cbind returns afterwards.  
Do you have better solution?

**Comment by hope-data-science** [comment]
I don't have the data.frame, so can not replicate your results. But I suggest you try `summarise_vars` to complete this task. Not sure if "{.col}_sum" can be used. Give it a try.

**Comment by kongdd** [comment]
The input file is at here. Only 1kb. 
[df_char.csv](https://github.com/hope-data-science/tidyfst/files/9175959/df_char.csv)

In my understanding, `summarise_vars` not suit for multiple `func`.

**Comment by hope-data-science** [comment]
So far, we can only use:
```
library(pacman)
p_load(tidyfst,dplyr)

fread("https://github.com/hope-data-science/tidyfst/files/9175959/df_char.csv") -> df_char

vars_mean <- c("u", "v", "speed", "angle")
vars_sum <- c("dist", "angle") # "u", "v"



df_char %>% 
  summarise_dt(
    duration = .N
  )

df_char %>% 
  summarise_vars(
    .func = list(mean,sum)
  )
```

**Comment by kongdd** [comment]
Got it. Thank u.
