### ISSUE TITLE
group_by_dt()为什么这么慢？

### ISSUE THREAD

**Issue by hwanghan** [hope-data-science/tidyfst#17]
同样的任务在分组时使用group_by和group_by_dt，速度差异非常大，是我使用的方式不对吗？
```
system.time(
govsub_cat %>% 
  group_by(stkcd, report_date) %>% 
  mutate_dt(sub_all_curr = sum(sub_curr, na.rm = T), sub_all_last = sum(sub_last, na.rm = T))
)

用户 系统 流逝 
0.96 0.01 0.97 
```

```
system.time(
  govsub_cat %>% 
    group_by_dt(cols = c("stkcd", "report_date")) %>% 
    group_exe_dt(mutate_dt(sub_all_curr = sum(sub_curr, na.rm = T), sub_all_last = sum(sub_last, na.rm = T)))
)

用户  系统  流逝 
16.13  0.23 16.25
```

**Comment by hope-data-science** [comment]
一般来说，`group_by`系列的函数在tidyfst包中都不快，它能够解决的是写代码的便利，但是在计算效率上不够好。在经常需要分组的函数中，一般都会有by参数，提供分组计算功能。比如你上面的任务，可以使用以下的代码尝试一下：
```
govsub_cat %>%
  mutate_dt(sub_all_curr = sum(sub_curr, na.rm = T), sub_all_last = sum(sub_last, na.rm = T), by = .(stkcd, report_date))
```

**Comment by hwanghan** [comment]
首先感谢您开发`tidyfst`这么好用的包。以上代码确实比原生`dplyr`快。另外还想请问一下，为什么`tidyfst`中的部分函数与`dplyr`的行为不一致。例如我刚才用到的`group_by`和`group_dt`。此外还有`group_by_dt`和`group_exe_dt`两个需要联用，这些与`dplyr`使用习惯不一致的函数，您是出于什么样的考虑呢？有没有可能将`tidyfst`与`dplyr`保持更大的一致性？

**Comment by hope-data-science** [comment]
感谢你使用tidyfst包。行为不一致是因为，tidyfst包的内核是data.table。从计算效率上来说，没有比data.table更好的工具。但是由于data.table的可读易写性能比较差，所以设计tidyfst包作为data.table的伴侣，此外用dplyr动词作为前缀方便dplyr用户转移。但是在实现中可以发现，由于dplyr和data.table底层不同，没有办法把所有功能都等量移植。此外，tidyfst也是为了更快地处理数据，也独立进行了很多为了便捷的尝试。比如tidyfst包没有across函数，但是`mutate_vars`和`summarise_vars`函数能够便捷的完成很多类似操作。同时，tidyfst包的`select_dt`函数在列选择上显然要比dplyr更加丰富强大。

如果希望提高一致性，首先有用户认为有足够的必要，其次在实现上也能够提供方案。其实还有别的包可以供你选择，比如dtplyr，这个一致性会很强，但是能够实现的功能与tidyfst比实在太少了。data.table本身是一门比dplyr更加丰富而底层的工具，tidyfst只是在其上进行的封装而已。如果你想要绝对的计算效率，学习data.table是未来必须的。tidyfst是我学习data.table后把很多常用功能集成化的结果，类dplyr的功能只是其中一部分，最终的目的还是简洁高效地实现所有常用数据操作。如果你对任何函数觉得有优化的空间，都可以提出建议，如果能够实现，都是可以考虑在外来融入系统内部的。

分组操作来说，一直是dplyr的弱项，一分组就慢，而data.table会快很多。不知道未来会不会有变化。其实还有另一种路径，是你去dplyr提一个issue，问一下是否能够让现在已有的dplyr更加快。这样才能够在不牺牲习惯的前提下，获得更高的效能。
