### ISSUE TITLE
ERROR: unable to collate and parse R files for package ‘tidyfst’

### ISSUE THREAD

**Issue by B-1991-ing** [hope-data-science/tidyfst#18]
Dear tidyfst support team,

As the screenshot shown that there is an error when I installed the R package - ‘tidyfst’ as suggested in the tutorial.
<img width="617" alt="Screenshot 2022-08-10 at 11 49 00" src="https://user-images.githubusercontent.com/54441633/183871588-33ad1c94-697d-4a4d-82b2-a9438626a683.png">

Could you give some suggestion according to your experience?

Thank you very much.

Best,

Bing

**Comment by hope-data-science** [comment]
I am wondering if you are using an R of lower version that do not support the function writing using `\`. If this is a problem, I can use the `function` instead of `\`. Currently, updating the R version might help.

**Comment by B-1991-ing** [comment]
Thank you very much for your reply. 

I am using the rstudio-server/1.3.1073 and R.4.0.0. I am not sure whether I can update the version or not. Because I am now running the R command line on the HPC platform, which I can only choose the current installed version I think.

<img width="893" alt="Screenshot 2022-08-10 at 12 11 38" src="https://user-images.githubusercontent.com/54441633/183876381-1a866617-9a0d-4178-88b8-fc4a76e5d17a.png">


Bing

**Comment by hope-data-science** [comment]
I am considering you can use the lower version of tidyfst, for instance 1.6.5, using:
```
require(devtools)
install_version("tidyfst", version = "1.6.5", repos = "http://cran.us.r-project.org")
```
Hope this can help.

**Comment by B-1991-ing** [comment]
Thank you very much for your suggestion. 

Looks like it works now.

<img width="762" alt="Screenshot 2022-08-10 at 12 17 19" src="https://user-images.githubusercontent.com/54441633/183877482-2d03b65b-9a7d-4944-b0e0-0885edeff3a6.png">

Best,

Bing
