### ISSUE TITLE
failed when install tidyfst-1.7.0 from CRAN

### ISSUE THREAD

**Issue by shenli-js** [hope-data-science/tidyfst#19]
* installing to library ‘/Business/psn_company/sc01/software/R-4.0.5/lib64/R/library’
* installing *source* package ‘tidyfst’ ...
** package ‘tidyfst’ successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) : 
  /tmp/Rtmp35lYmQ/R.INSTALL1bc6f47106d97/tidyfst/R/pkg_load.R:34:12: unexpected input
33: #' @export
34: pkg_load = \
               ^
ERROR: unable to collate and parse R files for package ‘tidyfst’
* removing ‘/Business/psn_company/sc01/software/R-4.0.5/lib64/R/library/tidyfst’

**Comment by hope-data-science** [comment]
Maybe it is because I use backslash (`\`) but not `function` to make functions? I have resubmitted to CRAN and hope it helps.
