### ISSUE TITLE
summarise_dt does not evaluate expression properly with grouping variable

### ISSUE THREAD

**Issue by jfdesomzee** [hope-data-science/tidyfst#20]
When by variable is used in field expression, this expression is not always properly evaluated

iris %>%
tidyfst::summarise_dt(Species_Fault=sum(ifelse(Species=="setosa",1,
ifelse(Species=="virginica",1,
ifelse(Sepal.Length<5,1,0)))),
by="Species") %>% tidyfst::count_dt(c("Species","Species_Fault"))

returns

![image](https://user-images.githubusercontent.com/26111904/187701582-099fee47-0486-43dc-9cd0-664f999f2807.png)

A work around is to duplicate the variable before aggregation but not so convenient.

Data %>%
tidyfst::mutate_dt(.Species=Species) %>%
tidyfst::summarise_dt(Species_Fault=sum(ifelse(.Species=="setosa",1,
ifelse(.Species=="virginica",1,
ifelse(Sepal.Length<5,1,0)))),
by="Species") %>% tidyfst::count_dt(c("Species","Species_Fault"))
![image](https://user-images.githubusercontent.com/26111904/187701507-a99a765c-de0a-4cc6-888c-74e34848a405.png)

Same behavior for mutate_dt

**Comment by hope-data-science** [comment]
Hello, thank you for using tidyfst. I am wondering what your are intending to achieve the the codes above. I think there might be more proper ways to accomplish it in tidyfst.

**Comment by jfdesomzee** [comment]
> Hello. I'm not trying to accomplish anything with the iris data. This is just a simple example but I have quite a lot of R code for data manipulation all written using dplyr. These includes plenty of mutate with group_by. In order to faster the process while keeping the same syntax (which is very nice) I'm transforming the code to data.table with tidyfst. This works pretty well, thanks. 
The only issue is that I sometimes use the by variable in the fields formula and this does not gives the expected results. Like in the example.
I'm of course more than welcome to any suggestion/work arround that makes the code proper and would solve the issue. Another way of coding the example could also bring inspiration.

**Comment by hope-data-science** [comment]
Thank you for the feedback. Still, I do not get the question you are explaining. Can you possibly use a simpler case as an example? I want to know: (1) What you are doing; (2) What results are expected; (3) What tidyfst currently yields. Then I can figure out why the codes do not work as you expect and try to fix it.

**Comment by jfdesomzee** [comment]
In this example, I want to aggregate iris by species. In case species is either setosa or virginica I want a simple count otherwise I only want to count the number of records having Sepal.Length < 5.
The expeted result is 
![image](https://user-images.githubusercontent.com/26111904/187858591-ac31b5e5-5ea7-4ffe-aa7d-362e80ddc693.png)
But this code
iris %>%
  tidyfst::summarise_dt(Species_Fault=sum(ifelse(Species=="setosa",1,
                                                 ifelse(Species=="virginica",1,
                                                        ifelse(Sepal.Length<5,1,0)))),
                        by="Species")
returns
![image](https://user-images.githubusercontent.com/26111904/187858868-bcff8935-de77-4a80-a401-e6e2e5b72118.png)

**Comment by hope-data-science** [comment]
I know what you want to do now, though I do not suggest this way of coding. You have two tasks but you want to do it in one function by using multiple `ifelse`. I suggest a workaround like this:
```
iris %>% 
  summarise_dt(
    no = .N,lala = sum(Sepal.Length < 5),by = Species
  ) %>% 
  mutate_dt(Species_Fault = ifelse(Species %in% c("setosa","virginica"),no,lala)) %>% 
  select_dt(Species,Species_Fault)
```

**Comment by jfdesomzee** [comment]
This would indeed solve the issue. The problem is the multiple ifelse approach was working with dplyr. And hence has been used, because it's faster to write and most probably faster to run (it computes only one fields instead of 3). 
And it's pretty hard to find where in the code adaptation is required. I'm thinking about adpating the summarise_dt (mutate_dt) in order to check in the formulas if we can find the by. In that case I'd return a warning.

**Comment by hope-data-science** [comment]
Conditional summarise or mutate might not be regarded as good practice, because when you can split them into two simple task, you should choose the simple way over the complex one. 
But I know your core question is can not use the dplyr syntax directly in tidyfst. Unfortunately, I think there is no shortcut to this. I suggest you try `dtplyr`， which lacks many functions `tidyfst` possess, but may keep the syntax better.

**Comment by jfdesomzee** [comment]
I tested dtplyr previoulsy but I kind of like your approach better. 
Anyway, with dtplyr I also have an issue

require(dtplyr)
Data <- iris %>% as.data.table

Data %>% 
  dplyr::group_by(Species) %>% 
  dplyr::mutate(Species_Fault=ifelse(Species=="setosa","S",
                                     ifelse(Species=="virginica","V",
                                            ifelse(row_number()<4,"E","F")))) %>% 
  dplyr::group_by(Species,Species_Fault) %>% 
  dplyr::summarise(n())
![image](https://user-images.githubusercontent.com/26111904/187883067-083eeda2-fa9b-4862-a8d7-152686dab198.png)


Data %>% 
  dplyr::mutate(Spec=Species) %>% 
  dplyr::group_by(Spec) %>% 
  dplyr::mutate(Species_Fault=ifelse(Species=="setosa","S",
                                     ifelse(Species=="virginica","V",
                                            ifelse(row_number()<4,"E","F")))) %>% 
  dplyr::group_by(Species,Species_Fault) %>% 
  dplyr::summarise(n())

![image](https://user-images.githubusercontent.com/26111904/187883147-f5de3c00-6d86-487a-ad67-3f5673776fd2.png)

**Comment by hope-data-science** [comment]
I do not quite get your problem. Maybe you can ask author of tidytable (<https://github.com/markfairbanks/tidytable>), this package also attempt to keep similar syntax as in dplyr.
