### ISSUE TITLE
conda上找不到tidyfst ?

### ISSUE THREAD

**Issue by lssb** [hope-data-science/tidyfst#22]
0.0

**Comment by hope-data-science** [comment]
应该可以找到的，不知道你是如何调用的，在服务器中使用吗

**Comment by lssb** [comment]
找不到呀，，不过我用CRAN装好了~

https://anaconda.org/search?q=tidyfst  
![image](https://user-images.githubusercontent.com/16911737/204798923-d42cda78-1c95-41f0-a8cf-5c488df5edca.png)

**Comment by hope-data-science** [comment]
OK
