### ISSUE TITLE
Unable to install the package normally

### ISSUE THREAD

**Issue by xiaoluolorn** [hope-data-science/tidyfst#23]
OS: Debian Bullseye
Platform: ARM64

Error in parse(outFile) : 
  /tmp/RtmppIrGoE/R.INSTALL9d54411f9e03/tidyfst/R/pkg_load.R:43:27: unexpected input
42:   if(length(new.packages)) install.packages(new.packages)
43:   sapply(list.of.packages,\
                              ^
ERROR: unable to collate and parse R files for package ‘tidyfst’

**Comment by hope-data-science** [comment]
I don't know how this error comes out, because all the CRAN checks are OK (see <https://cran.r-project.org/web/checks/check_results_tidyfst.html>).

**Comment by hope-data-science** [comment]
Would you please let me see your R version? I think this might be a problem because I write functions using the trick provided by R version later than 4.0.0.

**Comment by eclarsen-10** [comment]
Hi I am also having the same issue. My R version is 4.02

* installing *source* package 'tidyfst' ...
** package 'tidyfst' successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/User/AppData/Local/Temp/RtmpyKiXjL/R.INSTALL5f5860b4638/tidyfst/R/pkg_load.R:43:27: unexpected input
42:   if(length(new.packages)) install.packages(new.packages)
43:   sapply(list.of.packages,\
                              ^
ERROR: unable to collate and parse R files for package 'tidyfst'
* removing 'C:/Program Files/R/R-4.0.2/library/tidyfst'
Warning in install.packages :
  installation of package ‘tidyfst’ had non-zero exit status

**Comment by hope-data-science** [comment]
Thank you for the report. Is it addressed? Or can you send me your codes so I can check.
