### ISSUE TITLE
关于“mutate_dt”函数的问题

### ISSUE THREAD

**Issue by hyc173** [hope-data-science/tidyfst#24]
![屏幕截图 2023-03-02 145934](https://user-images.githubusercontent.com/72434270/222354510-8deb8271-2cc8-45e7-a4e0-ae0ea1ee9578.png)
问题如图所示，使用mutate_dt函数会报Error in factor(预测类别, levels = c("Pos", "Neg")) : object '预测类别' not found，使用mutate就可以正常运行。是两个函数有什么区别吗？还是我哪里写错了

**Comment by hope-data-science** [comment]
可以把你的原始代码粘贴过来吗？

**Comment by hyc173** [comment]
> 可以把你的原始代码粘贴过来吗？

library(tidyfst)
df = data.table(
  ID = 1:10, 
  真实类别 = c("Pos","Pos","Pos","Neg","Pos","Neg","Neg","Neg","Pos","Neg"),
  预测概率 = c(0.95,0.86,0.69,0.65,0.59,0.52,0.39,0.28,0.15,0.06))
c = 0.85
df1 = df %>% 
  mutate_dt(
    预测类别 = ifelse(预测概率 >= c, "Pos", "Neg"), 
    预测类别 = factor(预测类别, levels = c("Pos", "Neg")),
    真实类别 = factor(真实类别, levels = c("Pos", "Neg"))
  )

就是这个如果把mutate_dt换成mutate就能跑

**Comment by hyc173** [comment]
不知道是哪里写错了

**Comment by hope-data-science** [comment]
因为你的代码稍微有一些冗余，就是把一步能够操作好的分成了两步，就是对预测类别这一列的操作。dplyr可以支持这一类冗余操作，但是tidyfst认为你要对预测类别做操作，只能在一个mutate_dt中出现一次。所以如果要得到正确结果，可以：
```
library(tidyfst)
df = data.table(
  ID = 1:10,
  真实类别 = c("Pos","Pos","Pos","Neg","Pos","Neg","Neg","Neg","Pos","Neg"),
  预测概率 = c(0.95,0.86,0.69,0.65,0.59,0.52,0.39,0.28,0.15,0.06))
c = 0.85
df1 = df %>%
  mutate_dt(
    预测类别 = ifelse(预测概率 >= c, "Pos", "Neg") %>% 
      factor(levels = c("Pos", "Neg")),
    真实类别 = factor(真实类别, levels = c("Pos", "Neg"))
  )
df1
```

**Comment by hyc173** [comment]
多谢
