### ISSUE TITLE
Error with filter() when using lapply()

### ISSUE THREAD

**Issue by lluisfortes1** [hope-data-science/tidyfst#3]
I want to indicate, I've found both _tidyfst_ and _poorman_  package throws the [same error with the same calculus](https://github.com/nathaneastwood/poorman/issues/9)

The basic use of filter() works as expected:

```
a = as.data.table(iris)

sp1 = 'virginica'
filter(a, Species == sp1)
```

But when I want to create a list based on the factor level Species, it fails

```
sp2 = levels(a$Species)

lapply(sp2, function(x) {
  filter(a, Species == x)
})
```
Same if factor is used as character variable:

```
sp3 = unique(as.character(a$Species))

lapply(sp3, function(x) {
  filter(a, Species == x)
})
```

When using with dplyr, it's working correctly:

```
lapply(sp2, function(x) {
  dplyr::filter(a, Species == x)
})

lapply(sp3, function(x) {
  dplyr::filter(a, Species == x)
})
```

**Comment by hope-data-science** [comment]
I think this is just not what a `filter_dt` should do (tidyfst do not have the API `filter`, but named as `filter_dt`). If you want to get the similar results, try:
```
library(tidyfst)

a = as.data.table(iris)

split(a,by = "Species")
```
Using `filter_dt` is not correct for this case I think.

Thanks.

**Comment by lluisfortes1** [comment]
Sorry, I was thinking about _tidyft_

**Comment by hope-data-science** [comment]
It's OK, in this question, the answer is the same for both packages. If you want to split it, just use `split`. *tidyfst* and *tidyft* is not intending to resemble everything in *tidyverse* or any other tools. It is about how to bring the correct answers to you with the least pain. Further questions are more than welcome!

**Comment by lluisfortes1** [comment]
Thanks for your answer. I wanted to be organized and I've just wrote the same issue for _tidyft_ package....so sorry!! You can delete the other one ;p

**Comment by hope-data-science** [comment]
It's all right, let's just close it.
