### ISSUE TITLE
transmute_dt() behaves like summarize_dt() when using aggregation functions

### ISSUE THREAD

**Issue by markfairbanks** [hope-data-science/tidyfst#6]
`transmute_dt()` seems to work like `summarize_dt()` if aggregation functions are used.

``` r
library(tidyfst, warn.conflicts = FALSE)
#> 
#> Life's short, use R.

test_df <- data.table(x = 1:3, y = c("a", "a", "b"))

# Keeps all 3 rows
test_df %>%
  transmute_dt(double_x = x * 2)
#>    double_x
#>       <num>
#> 1:        2
#> 2:        4
#> 3:        6

# Aggregates data/loses rows
test_df %>%
  transmute_dt(avg_x = mean(x))
#>    avg_x
#>    <num>
#> 1:     2

test_df %>%
  summarize_dt(avg_x = mean(x))
#>    avg_x
#>    <num>
#> 1:     2
```

**Comment by hope-data-science** [comment]
I think they work correctly as you demands. When you use `mean` you usually aggregate (by group or not). The `summarize_dt` already gives you the correct answer. Now comes with `transmute_dt`, usually you generate a data.table with length > 1, the the results will come out recursively. Try:
```
test_df %>%
  transmute_dt(double_x = x * 2,avg_x = mean(x))
```
If you use aggregate functions only, you want less info. If you want to add to the original data.frame, use `mutate_dt`.

**Comment by markfairbanks** [comment]
A better example might be to show how it behaves when using `by`. It behaves differently than `dplyr`.

If this difference is intentional, I feel like it should be documented.

``` r
library(tidyfst, warn.conflicts = FALSE)
#> 
#> Life's short, use R.
library(dplyr, warn.conflicts = FALSE)

test_df <- data.table(x = 1:3, y = c("a", "a", "b"))

# tidyfst
test_df %>%
  transmute_dt(avg_x = mean(x), by = y)
#>         y avg_x
#>    <char> <num>
#> 1:      a   1.5
#> 2:      b   3.0

test_df %>%
  group_by(y) %>%
  transmute(avg_x = mean(x))
#> # A tibble: 3 x 2
#> # Groups:   y [2]
#>   y     avg_x
#>   <chr> <dbl>
#> 1 a       1.5
#> 2 a       1.5
#> 3 b       3
```

**Comment by hope-data-science** [comment]
I think you have made a point in this example. It would not be hard to fix it, as long as it makes sense. I'll make it run the way you present in the next released version.

**Comment by hope-data-science** [comment]
This has been fixed in the new codes(<https://github.com/hope-data-science/tidyfst/blob/master/R/mutate_dt.R>).

Thanks.
