### ISSUE TITLE
[JOSS Review] Non-portable filenames

### ISSUE THREAD

**Issue by tomsing1** [hope-data-science/tidyfst#7]
Thanks for submitting your paper to JOSS and for addressing so many of the comments already!

I just ran R CMD check and got the following error, related to filenames in your repo:

```
> checking for portable file names ... ERROR
  Found the following file with a non-portable file name:
    docs/R语言数据操纵之美_黄天元.pptx
  These are not valid file names on all R platforms.
  Please rename the files and try again.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
   WARNING
  Found the following files with non-portable file names:
    docs/R语言数据操纵之美_黄天元.pptx
    docs/reference/figures/hex-tidyfst .png
    man/figures/hex-tidyfst .png
  These are not fully portable file names.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
```

Perhaps you want to rename the three files (the last two have spurious spaces before the suffix)?
- docs/R语言数据操纵之美_黄天元.pptx
- docs/reference/figures/hex-tidyfst .png
- man/figures/hex-tidyfst .png

Best,
Thomas

**Comment by hope-data-science** [comment]
Thank you for the feedback. I've removed the figures which could still work for the current logo. And the file with filename of Chinese has been removed (have changed to an English name and should work later). Hope this time it could work well.

Thanks.

**Comment by tomsing1** [comment]
Great - thanks for addressing this so quickly!
