### ISSUE TITLE
Saving nested tibbles

### ISSUE THREAD

**Issue by maskegger** [hope-data-science/tidyfst#9]
Any ideas on how to write nested data frames to disk? `export_fst()` gives the following error

> Error in write_fst(x, path, compress, uniform_encoding) : 
>   Unknown type found in column

**Comment by hope-data-science** [comment]
I think to use such form, the underling codes from *fst* package could not work. In such case, I would suggest using *qs* package(https://cran.r-project.org/web/packages/qs/index.html), which might help.

**Comment by maskegger** [comment]
Thank you. Closing this for now.
